<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="AgentSkills\" />
    <Folder Include="Api\OpenAI\" />
    <Folder Include="Data\AI\" />
  </ItemGroup>

</Project>
